### ISSUE TITLE
Missing license file.

### ISSUE THREAD

**Issue by mkcor** [khaledpch/SpeechToText#1]
Bonjour,

Le projet m'a l'air très intéressant ! Pourriez-vous préciser la licence logicielle ? GPLv3 ?

Merci,
Marianne Corvellec

**Comment by khaledpch** [comment]
Bonjour 
oui c'est ça GPLv3 , en faite c'était mon projet de fin d'étude ,ça fait plus de trois ans maintenant mais dernièrement j'ai décidé de le mettre sous GitHub.
Mercii
